sudo: require
dist: xenial
language: bash
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended
  texlive-fonts-extra
script:
- bash test.sh
deploy:
  provider: releases
  api_key:
    secure: kEDZYdTb66957shFkEUqhqvn7H2V636l3jxVb7Y9hiq31j9dsrJdkgDQaivY0PxVDdOOeOVlq6tvsz1gC3ePns2nTFSpA7F5BHu9ywueyDx1Occei90hTaFozOmcjC8u4YU77763X1+Gw4RaqqPAbO5szD3GflD7NXUOguqVmmbL5Diu3qu1Gyrud/KFxzqleoJC/iAMNqh0KfUxKQN07+A6SJJKK447PLd9UVTgzZp5K0Ab1/PUtN1RatczU0/1dMpNTZ4SJ0pGJnEs1g9oVzdnubgTgNCoEoslXOphfrMj560xZmPV6Qs3nL1oWltJr2qXqcyMHy+yTQ4hyMlUr1hO/0+1FkRD6BYvVVzEmpKjfhKyjooUNObE//4VGnQ4PUt/2SDfoJT7c8Wu9ZzuTkt+DQb1x78Vyr5TAuJl33hFCyh+AE1/id/w/J0RRfwQGTDKVpVmfRmpqwwq8XbdcDVExOAC4U5yvipgV+nVJqo44QkuSAbBtkFDYqWKcXjHo6fGJPjJ8+g0Y2zYoa03kjpUtlhEMUT/cGENpTYKlfJjHcgdHlpC5krQQTL/PtuW65k67X4QuvkaQFsSu+QY05q+ND5BL5wgl1QAOOrM21YuxzCF8Cws+srJ7/hUPYtEMdCQAGRjUwRYVpJySFfwKrPnoReFB025AU6Sz7rEq9U=
  file: 
  - Document.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
