name: Latex-multicompiler
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1
    - name: Latex compiler
      uses: Jatus93/Latex-multicompiler@master
      with:
        entryPoint: ./
